services:
  cp-config:
    image: gabriel0simpleg/cp-config
    ports:
      - "80:3000"
    environment:
      - SECRETS_MANAGER_ACCESS_TOKEN=${SECRETS_MANAGER_ACCESS_TOKEN}
    volumes:
      - ./config:/cp-config/config # Change to your cp-config root path